### ISSUE TITLE
Add more sophisticated data processing

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/polartools#1]
Use Matt's [Larch](https://xraypy.github.io/xraylarch/index.html) package. Replace `numpy.polyfit` with [lmfit](https://github.com/lmfit/lmfit-py)

**Comment by prjemian** [comment]
Nice call

**Comment by gfabbris** [comment]
**NOTE**: `larch` has "straight python" functions, see for instance [`larch.xafs.preedge`](https://github.com/xraypy/xraylarch/blob/d737a02e4db7070591472b777772ffb3d0c98613/larch/xafs/pre_edge.py#L91).
