### ISSUE TITLE
Code quality check?

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/polartools#6]
@prjemian: I noticed you have a couple of code quality checkers in `apstools`. Should I add both here as well?

**Comment by prjemian** [comment]
Yes.  Use flake8 (in a github actions worfklow) for code style and 
Codacy for quality checks.  The LGTM has been good to me but is getting 
to be slow.  Still, it catches items not caught by Codacy.

**Comment by gfabbris** [comment]
Should I separate flake8 from unit test workflow?
